pipeline { // test 1
    agent any
    environment {
        AWS_ACCOUNT_ID = '017820660901'
        AWS_REGION = 'ap-northeast-2'
        ECR_REPO_NAME = 'comment-service'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        GIT_CREDENTIALS_ID = 'github-credentials'
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/ghtjr410/Miniblog-K8s-Microservices-Stack.git',
                    credentialsId: "${GIT_CREDENTIALS_ID}"
            }
        }
        stage('Check Tools') {
            steps {
                bat '''
                    aws --version
                    docker --version
                '''
            }
        }
        stage('Print AWS Identity') {
            steps {
                withAWS(region: "${AWS_REGION}", credentials: 'aws-credentials') {
                    bat '''
                        aws sts get-caller-identity
                    '''
                }
            }
        }

        stage('Login to ECR') {
            when {
                changeset "comment-service/**"
            }
            steps {
                withAWS(region: "${AWS_REGION}", credentials: 'aws-credentials') {
                    bat '''
                        aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 017820660901.dkr.ecr.ap-northeast-2.amazonaws.com
                    '''
                }
            }
        }
        stage('Verify ECR Login') {
            when {
                changeset "comment-service/**"
            }
            steps {
                withAWS(region: "${AWS_REGION}", credentials: 'aws-credentials') {
                    bat '''
                        aws ecr describe-repositories --region ap-northeast-2
                        if %ERRORLEVEL% EQU 0 (
                            echo Successfully listed ECR repositories.
                        ) else (
                            echo Failed to list ECR repositories.
                            exit /b 1
                        )
                    '''
                }
            }
        }
        stage('Build Docker Image') {
            when {
                changeset "comment-service/**"
            }
            steps {
                script {
                    docker.build("017820660901.dkr.ecr.ap-northeast-2.amazonaws.com/comment-service:${IMAGE_TAG}", 'comment-service/.')
                }
            }
        }
        stage('Push Docker Image to ECR') {
            when {
                changeset "comment-service/**"
            }
            steps {
                script {
                    docker.image("017820660901.dkr.ecr.ap-northeast-2.amazonaws.com/comment-service:${IMAGE_TAG}").push()
                }
            }
        }
        stage('Deploy to EKS') {
            when {
                changeset "comment-service/**"
            }
            steps {
                dir('charts/application') {
                    script {
                        withCredentials([
                            string(credentialsId: 'ecr-image-repo-url', variable: 'ECR_IMAGE_REPO_URL'),
                            string(credentialsId: 'aws-db-url', variable: 'AWS_DB_URL'),
                            string(credentialsId: 'aws-db-username', variable: 'AWS_DB_USERNAME'),
                            string(credentialsId: 'aws-db-password', variable: 'AWS_DB_PASSWORD'),
                        ]) {
                            bat """
                                echo Current Directory: %CD%
                                echo AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID}
                                echo AWS_REGION: ${AWS_REGION}
                                echo ECR_REPO_NAME: ${ECR_REPO_NAME}
                                echo IMAGE_TAG: ${IMAGE_TAG}
                                helm upgrade --install comment-service ./comment-service ^
                                    --set image.repository=${ECR_IMAGE_REPO_URL} ^
                                    --set image.tag=${IMAGE_TAG}
                                    --set aws.db.url=${AWS_DB_URL} ^
                                    --set aws.db.username=${AWS_DB_USERNAME} ^
                                    --set aws.db.password=${AWS_DB_PASSWORD}
                            """
                        }
                    }
                }
            }
        }
    }
}