apiVersion: v1
kind: Service
metadata:
  namespace: miniblog
  name: api-gateway-service
spec:
  selector:
    app: api-gateway-deployment
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
  type: ClusterIP