apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: miniblog
  name: account-service-deployment
  labels:
    app: account-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service-deployment
  template:
    metadata:
      labels:
        app: account-service-deployment
    spec:
      containers:
        - name: account-service
          image: {{ .Values.image.repository }}/account-service:{{ .Values.image.tag }}
          ports:
            - containerPort: 4049
          env:
            - name: SPRING_APPLICATION_NAME
              value: "account-service"
            - name: SERVER_PORT
              value: "4049"
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: "https://keycloak.ghtjr.com"
            - name: KEYCLOAK_CREDENTIALS_SECRET
              value: {{ .Values.keycloak.secret | quote}}
            - name: LOKI_URL
              value: "http://loki:3100/loki/api/v1/push"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://tempo:9411/api/v2/spans"
            - name: SPRING_DATASOURCE_URI
              value: {{ .Values.azure.db.url | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.azure.db.username | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.azure.db.password | quote }}
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "broker-service:9092"
            - name: SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL
              value: "http://schema-registry-service:8085"
