apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: miniblog
  labels:
    app: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-deployment
  template:
    metadata:
      labels:
        app: mongodb-deployment
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0.5
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: MONGO_DB_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: MONGO_DB_PASSWORD
            - name: MONGO_INITDB_DATABASE
              value: MONGO_DB_DATABASE
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
