/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.miniblog.profile.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProfileCreatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6258455289031381924L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProfileCreatedEvent\",\"namespace\":\"com.miniblog.profile.avro\",\"fields\":[{\"name\":\"profileUuid\",\"type\":\"string\"},{\"name\":\"userUuid\",\"type\":\"string\"},{\"name\":\"nickname\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"intro\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProfileCreatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProfileCreatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProfileCreatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProfileCreatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProfileCreatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProfileCreatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProfileCreatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProfileCreatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProfileCreatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence profileUuid;
  private java.lang.CharSequence userUuid;
  private java.lang.CharSequence nickname;
  private java.lang.CharSequence email;
  private java.lang.CharSequence title;
  private java.lang.CharSequence intro;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProfileCreatedEvent() {}

  /**
   * All-args constructor.
   * @param profileUuid The new value for profileUuid
   * @param userUuid The new value for userUuid
   * @param nickname The new value for nickname
   * @param email The new value for email
   * @param title The new value for title
   * @param intro The new value for intro
   */
  public ProfileCreatedEvent(java.lang.CharSequence profileUuid, java.lang.CharSequence userUuid, java.lang.CharSequence nickname, java.lang.CharSequence email, java.lang.CharSequence title, java.lang.CharSequence intro) {
    this.profileUuid = profileUuid;
    this.userUuid = userUuid;
    this.nickname = nickname;
    this.email = email;
    this.title = title;
    this.intro = intro;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return profileUuid;
    case 1: return userUuid;
    case 2: return nickname;
    case 3: return email;
    case 4: return title;
    case 5: return intro;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: profileUuid = (java.lang.CharSequence)value$; break;
    case 1: userUuid = (java.lang.CharSequence)value$; break;
    case 2: nickname = (java.lang.CharSequence)value$; break;
    case 3: email = (java.lang.CharSequence)value$; break;
    case 4: title = (java.lang.CharSequence)value$; break;
    case 5: intro = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'profileUuid' field.
   * @return The value of the 'profileUuid' field.
   */
  public java.lang.CharSequence getProfileUuid() {
    return profileUuid;
  }


  /**
   * Sets the value of the 'profileUuid' field.
   * @param value the value to set.
   */
  public void setProfileUuid(java.lang.CharSequence value) {
    this.profileUuid = value;
  }

  /**
   * Gets the value of the 'userUuid' field.
   * @return The value of the 'userUuid' field.
   */
  public java.lang.CharSequence getUserUuid() {
    return userUuid;
  }


  /**
   * Sets the value of the 'userUuid' field.
   * @param value the value to set.
   */
  public void setUserUuid(java.lang.CharSequence value) {
    this.userUuid = value;
  }

  /**
   * Gets the value of the 'nickname' field.
   * @return The value of the 'nickname' field.
   */
  public java.lang.CharSequence getNickname() {
    return nickname;
  }


  /**
   * Sets the value of the 'nickname' field.
   * @param value the value to set.
   */
  public void setNickname(java.lang.CharSequence value) {
    this.nickname = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'intro' field.
   * @return The value of the 'intro' field.
   */
  public java.lang.CharSequence getIntro() {
    return intro;
  }


  /**
   * Sets the value of the 'intro' field.
   * @param value the value to set.
   */
  public void setIntro(java.lang.CharSequence value) {
    this.intro = value;
  }

  /**
   * Creates a new ProfileCreatedEvent RecordBuilder.
   * @return A new ProfileCreatedEvent RecordBuilder
   */
  public static com.miniblog.profile.avro.ProfileCreatedEvent.Builder newBuilder() {
    return new com.miniblog.profile.avro.ProfileCreatedEvent.Builder();
  }

  /**
   * Creates a new ProfileCreatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProfileCreatedEvent RecordBuilder
   */
  public static com.miniblog.profile.avro.ProfileCreatedEvent.Builder newBuilder(com.miniblog.profile.avro.ProfileCreatedEvent.Builder other) {
    if (other == null) {
      return new com.miniblog.profile.avro.ProfileCreatedEvent.Builder();
    } else {
      return new com.miniblog.profile.avro.ProfileCreatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new ProfileCreatedEvent RecordBuilder by copying an existing ProfileCreatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new ProfileCreatedEvent RecordBuilder
   */
  public static com.miniblog.profile.avro.ProfileCreatedEvent.Builder newBuilder(com.miniblog.profile.avro.ProfileCreatedEvent other) {
    if (other == null) {
      return new com.miniblog.profile.avro.ProfileCreatedEvent.Builder();
    } else {
      return new com.miniblog.profile.avro.ProfileCreatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProfileCreatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProfileCreatedEvent>
    implements org.apache.avro.data.RecordBuilder<ProfileCreatedEvent> {

    private java.lang.CharSequence profileUuid;
    private java.lang.CharSequence userUuid;
    private java.lang.CharSequence nickname;
    private java.lang.CharSequence email;
    private java.lang.CharSequence title;
    private java.lang.CharSequence intro;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.miniblog.profile.avro.ProfileCreatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.profileUuid)) {
        this.profileUuid = data().deepCopy(fields()[0].schema(), other.profileUuid);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.userUuid)) {
        this.userUuid = data().deepCopy(fields()[1].schema(), other.userUuid);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.nickname)) {
        this.nickname = data().deepCopy(fields()[2].schema(), other.nickname);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.email)) {
        this.email = data().deepCopy(fields()[3].schema(), other.email);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.title)) {
        this.title = data().deepCopy(fields()[4].schema(), other.title);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.intro)) {
        this.intro = data().deepCopy(fields()[5].schema(), other.intro);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing ProfileCreatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.miniblog.profile.avro.ProfileCreatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.profileUuid)) {
        this.profileUuid = data().deepCopy(fields()[0].schema(), other.profileUuid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userUuid)) {
        this.userUuid = data().deepCopy(fields()[1].schema(), other.userUuid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.nickname)) {
        this.nickname = data().deepCopy(fields()[2].schema(), other.nickname);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.email)) {
        this.email = data().deepCopy(fields()[3].schema(), other.email);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.title)) {
        this.title = data().deepCopy(fields()[4].schema(), other.title);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.intro)) {
        this.intro = data().deepCopy(fields()[5].schema(), other.intro);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'profileUuid' field.
      * @return The value.
      */
    public java.lang.CharSequence getProfileUuid() {
      return profileUuid;
    }


    /**
      * Sets the value of the 'profileUuid' field.
      * @param value The value of 'profileUuid'.
      * @return This builder.
      */
    public com.miniblog.profile.avro.ProfileCreatedEvent.Builder setProfileUuid(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.profileUuid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'profileUuid' field has been set.
      * @return True if the 'profileUuid' field has been set, false otherwise.
      */
    public boolean hasProfileUuid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'profileUuid' field.
      * @return This builder.
      */
    public com.miniblog.profile.avro.ProfileCreatedEvent.Builder clearProfileUuid() {
      profileUuid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'userUuid' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserUuid() {
      return userUuid;
    }


    /**
      * Sets the value of the 'userUuid' field.
      * @param value The value of 'userUuid'.
      * @return This builder.
      */
    public com.miniblog.profile.avro.ProfileCreatedEvent.Builder setUserUuid(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.userUuid = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'userUuid' field has been set.
      * @return True if the 'userUuid' field has been set, false otherwise.
      */
    public boolean hasUserUuid() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'userUuid' field.
      * @return This builder.
      */
    public com.miniblog.profile.avro.ProfileCreatedEvent.Builder clearUserUuid() {
      userUuid = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'nickname' field.
      * @return The value.
      */
    public java.lang.CharSequence getNickname() {
      return nickname;
    }


    /**
      * Sets the value of the 'nickname' field.
      * @param value The value of 'nickname'.
      * @return This builder.
      */
    public com.miniblog.profile.avro.ProfileCreatedEvent.Builder setNickname(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.nickname = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'nickname' field has been set.
      * @return True if the 'nickname' field has been set, false otherwise.
      */
    public boolean hasNickname() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'nickname' field.
      * @return This builder.
      */
    public com.miniblog.profile.avro.ProfileCreatedEvent.Builder clearNickname() {
      nickname = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.miniblog.profile.avro.ProfileCreatedEvent.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.email = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.miniblog.profile.avro.ProfileCreatedEvent.Builder clearEmail() {
      email = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public com.miniblog.profile.avro.ProfileCreatedEvent.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.title = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public com.miniblog.profile.avro.ProfileCreatedEvent.Builder clearTitle() {
      title = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'intro' field.
      * @return The value.
      */
    public java.lang.CharSequence getIntro() {
      return intro;
    }


    /**
      * Sets the value of the 'intro' field.
      * @param value The value of 'intro'.
      * @return This builder.
      */
    public com.miniblog.profile.avro.ProfileCreatedEvent.Builder setIntro(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.intro = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'intro' field has been set.
      * @return True if the 'intro' field has been set, false otherwise.
      */
    public boolean hasIntro() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'intro' field.
      * @return This builder.
      */
    public com.miniblog.profile.avro.ProfileCreatedEvent.Builder clearIntro() {
      intro = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProfileCreatedEvent build() {
      try {
        ProfileCreatedEvent record = new ProfileCreatedEvent();
        record.profileUuid = fieldSetFlags()[0] ? this.profileUuid : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.userUuid = fieldSetFlags()[1] ? this.userUuid : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.nickname = fieldSetFlags()[2] ? this.nickname : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.email = fieldSetFlags()[3] ? this.email : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.title = fieldSetFlags()[4] ? this.title : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.intro = fieldSetFlags()[5] ? this.intro : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProfileCreatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProfileCreatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProfileCreatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<ProfileCreatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.profileUuid);

    out.writeString(this.userUuid);

    out.writeString(this.nickname);

    out.writeString(this.email);

    out.writeString(this.title);

    out.writeString(this.intro);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.profileUuid = in.readString(this.profileUuid instanceof Utf8 ? (Utf8)this.profileUuid : null);

      this.userUuid = in.readString(this.userUuid instanceof Utf8 ? (Utf8)this.userUuid : null);

      this.nickname = in.readString(this.nickname instanceof Utf8 ? (Utf8)this.nickname : null);

      this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);

      this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);

      this.intro = in.readString(this.intro instanceof Utf8 ? (Utf8)this.intro : null);

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.profileUuid = in.readString(this.profileUuid instanceof Utf8 ? (Utf8)this.profileUuid : null);
          break;

        case 1:
          this.userUuid = in.readString(this.userUuid instanceof Utf8 ? (Utf8)this.userUuid : null);
          break;

        case 2:
          this.nickname = in.readString(this.nickname instanceof Utf8 ? (Utf8)this.nickname : null);
          break;

        case 3:
          this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
          break;

        case 4:
          this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);
          break;

        case 5:
          this.intro = in.readString(this.intro instanceof Utf8 ? (Utf8)this.intro : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










