apiVersion: v1
kind: Service
metadata:
  namespace: miniblog
  name: post-service-service
spec:
  selector:
    app: post-service-deployment
  ports:
    - protocol: TCP
      port: 4042
      targetPort: 4042
  type: ClusterIP
