apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: miniblog
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
