apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: miniblog
  name: blog-front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blog-front-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blog-front-deployment
    spec:
      containers:
        - image: 017820660901.dkr.ecr.ap-northeast-2.amazonaws.com/blog-front:{{ .Values.image.tag}}
          imagePullPolicy: Always
          name: blog-front-deployment
          ports:
            - containerPort: 80