apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-deployment
    spec:
      containers:
          - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            name: {{ .Release.Name }}-deployment
            ports:
                - containerPort: {{ .Values.service.port }}