apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: miniblog
  name: blog-front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blog-front-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blog-front-deployment
    spec:
      containers:
        - image: {{ECR_IMAGE_REPO_URL}}/blog-front:latest
          imagePullPolicy: Always
          name: blog-front-deployment
          ports:
            - containerPort: 80