apiVersion: v1
kind: Service
metadata:
  namespace: miniblog
  name: blog-front-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: blog-front-deployment