/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.miniblog.profile.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProfileUpdatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1535197641329405010L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProfileUpdatedEvent\",\"namespace\":\"com.miniblog.profile.avro\",\"fields\":[{\"name\":\"profileUuid\",\"type\":\"string\"},{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"intro\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProfileUpdatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProfileUpdatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProfileUpdatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProfileUpdatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProfileUpdatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProfileUpdatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProfileUpdatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProfileUpdatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProfileUpdatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence profileUuid;
  private java.lang.CharSequence title;
  private java.lang.CharSequence intro;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProfileUpdatedEvent() {}

  /**
   * All-args constructor.
   * @param profileUuid The new value for profileUuid
   * @param title The new value for title
   * @param intro The new value for intro
   */
  public ProfileUpdatedEvent(java.lang.CharSequence profileUuid, java.lang.CharSequence title, java.lang.CharSequence intro) {
    this.profileUuid = profileUuid;
    this.title = title;
    this.intro = intro;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return profileUuid;
    case 1: return title;
    case 2: return intro;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: profileUuid = (java.lang.CharSequence)value$; break;
    case 1: title = (java.lang.CharSequence)value$; break;
    case 2: intro = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'profileUuid' field.
   * @return The value of the 'profileUuid' field.
   */
  public java.lang.CharSequence getProfileUuid() {
    return profileUuid;
  }


  /**
   * Sets the value of the 'profileUuid' field.
   * @param value the value to set.
   */
  public void setProfileUuid(java.lang.CharSequence value) {
    this.profileUuid = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'intro' field.
   * @return The value of the 'intro' field.
   */
  public java.lang.CharSequence getIntro() {
    return intro;
  }


  /**
   * Sets the value of the 'intro' field.
   * @param value the value to set.
   */
  public void setIntro(java.lang.CharSequence value) {
    this.intro = value;
  }

  /**
   * Creates a new ProfileUpdatedEvent RecordBuilder.
   * @return A new ProfileUpdatedEvent RecordBuilder
   */
  public static com.miniblog.profile.avro.ProfileUpdatedEvent.Builder newBuilder() {
    return new com.miniblog.profile.avro.ProfileUpdatedEvent.Builder();
  }

  /**
   * Creates a new ProfileUpdatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProfileUpdatedEvent RecordBuilder
   */
  public static com.miniblog.profile.avro.ProfileUpdatedEvent.Builder newBuilder(com.miniblog.profile.avro.ProfileUpdatedEvent.Builder other) {
    if (other == null) {
      return new com.miniblog.profile.avro.ProfileUpdatedEvent.Builder();
    } else {
      return new com.miniblog.profile.avro.ProfileUpdatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new ProfileUpdatedEvent RecordBuilder by copying an existing ProfileUpdatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new ProfileUpdatedEvent RecordBuilder
   */
  public static com.miniblog.profile.avro.ProfileUpdatedEvent.Builder newBuilder(com.miniblog.profile.avro.ProfileUpdatedEvent other) {
    if (other == null) {
      return new com.miniblog.profile.avro.ProfileUpdatedEvent.Builder();
    } else {
      return new com.miniblog.profile.avro.ProfileUpdatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProfileUpdatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProfileUpdatedEvent>
    implements org.apache.avro.data.RecordBuilder<ProfileUpdatedEvent> {

    private java.lang.CharSequence profileUuid;
    private java.lang.CharSequence title;
    private java.lang.CharSequence intro;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.miniblog.profile.avro.ProfileUpdatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.profileUuid)) {
        this.profileUuid = data().deepCopy(fields()[0].schema(), other.profileUuid);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.intro)) {
        this.intro = data().deepCopy(fields()[2].schema(), other.intro);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ProfileUpdatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.miniblog.profile.avro.ProfileUpdatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.profileUuid)) {
        this.profileUuid = data().deepCopy(fields()[0].schema(), other.profileUuid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.intro)) {
        this.intro = data().deepCopy(fields()[2].schema(), other.intro);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'profileUuid' field.
      * @return The value.
      */
    public java.lang.CharSequence getProfileUuid() {
      return profileUuid;
    }


    /**
      * Sets the value of the 'profileUuid' field.
      * @param value The value of 'profileUuid'.
      * @return This builder.
      */
    public com.miniblog.profile.avro.ProfileUpdatedEvent.Builder setProfileUuid(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.profileUuid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'profileUuid' field has been set.
      * @return True if the 'profileUuid' field has been set, false otherwise.
      */
    public boolean hasProfileUuid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'profileUuid' field.
      * @return This builder.
      */
    public com.miniblog.profile.avro.ProfileUpdatedEvent.Builder clearProfileUuid() {
      profileUuid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public com.miniblog.profile.avro.ProfileUpdatedEvent.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.title = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public com.miniblog.profile.avro.ProfileUpdatedEvent.Builder clearTitle() {
      title = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'intro' field.
      * @return The value.
      */
    public java.lang.CharSequence getIntro() {
      return intro;
    }


    /**
      * Sets the value of the 'intro' field.
      * @param value The value of 'intro'.
      * @return This builder.
      */
    public com.miniblog.profile.avro.ProfileUpdatedEvent.Builder setIntro(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.intro = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'intro' field has been set.
      * @return True if the 'intro' field has been set, false otherwise.
      */
    public boolean hasIntro() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'intro' field.
      * @return This builder.
      */
    public com.miniblog.profile.avro.ProfileUpdatedEvent.Builder clearIntro() {
      intro = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProfileUpdatedEvent build() {
      try {
        ProfileUpdatedEvent record = new ProfileUpdatedEvent();
        record.profileUuid = fieldSetFlags()[0] ? this.profileUuid : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.title = fieldSetFlags()[1] ? this.title : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.intro = fieldSetFlags()[2] ? this.intro : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProfileUpdatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProfileUpdatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProfileUpdatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<ProfileUpdatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.profileUuid);

    out.writeString(this.title);

    out.writeString(this.intro);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.profileUuid = in.readString(this.profileUuid instanceof Utf8 ? (Utf8)this.profileUuid : null);

      this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);

      this.intro = in.readString(this.intro instanceof Utf8 ? (Utf8)this.intro : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.profileUuid = in.readString(this.profileUuid instanceof Utf8 ? (Utf8)this.profileUuid : null);
          break;

        case 1:
          this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);
          break;

        case 2:
          this.intro = in.readString(this.intro instanceof Utf8 ? (Utf8)this.intro : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










