apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: miniblog
data:
  tempo.yaml: |
    server:
      http_listen_port: 3110

    distributor:
      receivers:
        zipkin:

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks
