apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: miniblog
  labels:
    app: tempo
spec:
  selector:
    app: tempo
  ports:
    - protocol: TCP
      port: 3110
      targetPort: 3110
      name: tempo
    - protocol: TCP
      port: 9411
      targetPort: 9411
      name: zipkin
