/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.miniblog.account.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AccountDeletedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5859818438920795734L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AccountDeletedEvent\",\"namespace\":\"com.miniblog.account.avro\",\"fields\":[{\"name\":\"userUuid\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AccountDeletedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AccountDeletedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AccountDeletedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AccountDeletedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AccountDeletedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AccountDeletedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AccountDeletedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AccountDeletedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AccountDeletedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence userUuid;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AccountDeletedEvent() {}

  /**
   * All-args constructor.
   * @param userUuid The new value for userUuid
   */
  public AccountDeletedEvent(java.lang.CharSequence userUuid) {
    this.userUuid = userUuid;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userUuid;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userUuid = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userUuid' field.
   * @return The value of the 'userUuid' field.
   */
  public java.lang.CharSequence getUserUuid() {
    return userUuid;
  }


  /**
   * Sets the value of the 'userUuid' field.
   * @param value the value to set.
   */
  public void setUserUuid(java.lang.CharSequence value) {
    this.userUuid = value;
  }

  /**
   * Creates a new AccountDeletedEvent RecordBuilder.
   * @return A new AccountDeletedEvent RecordBuilder
   */
  public static com.miniblog.account.avro.AccountDeletedEvent.Builder newBuilder() {
    return new com.miniblog.account.avro.AccountDeletedEvent.Builder();
  }

  /**
   * Creates a new AccountDeletedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AccountDeletedEvent RecordBuilder
   */
  public static com.miniblog.account.avro.AccountDeletedEvent.Builder newBuilder(com.miniblog.account.avro.AccountDeletedEvent.Builder other) {
    if (other == null) {
      return new com.miniblog.account.avro.AccountDeletedEvent.Builder();
    } else {
      return new com.miniblog.account.avro.AccountDeletedEvent.Builder(other);
    }
  }

  /**
   * Creates a new AccountDeletedEvent RecordBuilder by copying an existing AccountDeletedEvent instance.
   * @param other The existing instance to copy.
   * @return A new AccountDeletedEvent RecordBuilder
   */
  public static com.miniblog.account.avro.AccountDeletedEvent.Builder newBuilder(com.miniblog.account.avro.AccountDeletedEvent other) {
    if (other == null) {
      return new com.miniblog.account.avro.AccountDeletedEvent.Builder();
    } else {
      return new com.miniblog.account.avro.AccountDeletedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for AccountDeletedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AccountDeletedEvent>
    implements org.apache.avro.data.RecordBuilder<AccountDeletedEvent> {

    private java.lang.CharSequence userUuid;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.miniblog.account.avro.AccountDeletedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userUuid)) {
        this.userUuid = data().deepCopy(fields()[0].schema(), other.userUuid);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing AccountDeletedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.miniblog.account.avro.AccountDeletedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.userUuid)) {
        this.userUuid = data().deepCopy(fields()[0].schema(), other.userUuid);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'userUuid' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserUuid() {
      return userUuid;
    }


    /**
      * Sets the value of the 'userUuid' field.
      * @param value The value of 'userUuid'.
      * @return This builder.
      */
    public com.miniblog.account.avro.AccountDeletedEvent.Builder setUserUuid(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.userUuid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userUuid' field has been set.
      * @return True if the 'userUuid' field has been set, false otherwise.
      */
    public boolean hasUserUuid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userUuid' field.
      * @return This builder.
      */
    public com.miniblog.account.avro.AccountDeletedEvent.Builder clearUserUuid() {
      userUuid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AccountDeletedEvent build() {
      try {
        AccountDeletedEvent record = new AccountDeletedEvent();
        record.userUuid = fieldSetFlags()[0] ? this.userUuid : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AccountDeletedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<AccountDeletedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AccountDeletedEvent>
    READER$ = (org.apache.avro.io.DatumReader<AccountDeletedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.userUuid);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.userUuid = in.readString(this.userUuid instanceof Utf8 ? (Utf8)this.userUuid : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.userUuid = in.readString(this.userUuid instanceof Utf8 ? (Utf8)this.userUuid : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










