/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.miniblog.like.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LikeCreatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1574398451276016298L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LikeCreatedEvent\",\"namespace\":\"com.miniblog.like.avro\",\"fields\":[{\"name\":\"likeUuid\",\"type\":\"string\"},{\"name\":\"postUuid\",\"type\":\"string\"},{\"name\":\"userUuid\",\"type\":\"string\"},{\"name\":\"createdDate\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LikeCreatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LikeCreatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LikeCreatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LikeCreatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LikeCreatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LikeCreatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LikeCreatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LikeCreatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LikeCreatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence likeUuid;
  private java.lang.CharSequence postUuid;
  private java.lang.CharSequence userUuid;
  private long createdDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LikeCreatedEvent() {}

  /**
   * All-args constructor.
   * @param likeUuid The new value for likeUuid
   * @param postUuid The new value for postUuid
   * @param userUuid The new value for userUuid
   * @param createdDate The new value for createdDate
   */
  public LikeCreatedEvent(java.lang.CharSequence likeUuid, java.lang.CharSequence postUuid, java.lang.CharSequence userUuid, java.lang.Long createdDate) {
    this.likeUuid = likeUuid;
    this.postUuid = postUuid;
    this.userUuid = userUuid;
    this.createdDate = createdDate;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return likeUuid;
    case 1: return postUuid;
    case 2: return userUuid;
    case 3: return createdDate;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: likeUuid = (java.lang.CharSequence)value$; break;
    case 1: postUuid = (java.lang.CharSequence)value$; break;
    case 2: userUuid = (java.lang.CharSequence)value$; break;
    case 3: createdDate = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'likeUuid' field.
   * @return The value of the 'likeUuid' field.
   */
  public java.lang.CharSequence getLikeUuid() {
    return likeUuid;
  }


  /**
   * Sets the value of the 'likeUuid' field.
   * @param value the value to set.
   */
  public void setLikeUuid(java.lang.CharSequence value) {
    this.likeUuid = value;
  }

  /**
   * Gets the value of the 'postUuid' field.
   * @return The value of the 'postUuid' field.
   */
  public java.lang.CharSequence getPostUuid() {
    return postUuid;
  }


  /**
   * Sets the value of the 'postUuid' field.
   * @param value the value to set.
   */
  public void setPostUuid(java.lang.CharSequence value) {
    this.postUuid = value;
  }

  /**
   * Gets the value of the 'userUuid' field.
   * @return The value of the 'userUuid' field.
   */
  public java.lang.CharSequence getUserUuid() {
    return userUuid;
  }


  /**
   * Sets the value of the 'userUuid' field.
   * @param value the value to set.
   */
  public void setUserUuid(java.lang.CharSequence value) {
    this.userUuid = value;
  }

  /**
   * Gets the value of the 'createdDate' field.
   * @return The value of the 'createdDate' field.
   */
  public long getCreatedDate() {
    return createdDate;
  }


  /**
   * Sets the value of the 'createdDate' field.
   * @param value the value to set.
   */
  public void setCreatedDate(long value) {
    this.createdDate = value;
  }

  /**
   * Creates a new LikeCreatedEvent RecordBuilder.
   * @return A new LikeCreatedEvent RecordBuilder
   */
  public static com.miniblog.like.avro.LikeCreatedEvent.Builder newBuilder() {
    return new com.miniblog.like.avro.LikeCreatedEvent.Builder();
  }

  /**
   * Creates a new LikeCreatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LikeCreatedEvent RecordBuilder
   */
  public static com.miniblog.like.avro.LikeCreatedEvent.Builder newBuilder(com.miniblog.like.avro.LikeCreatedEvent.Builder other) {
    if (other == null) {
      return new com.miniblog.like.avro.LikeCreatedEvent.Builder();
    } else {
      return new com.miniblog.like.avro.LikeCreatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new LikeCreatedEvent RecordBuilder by copying an existing LikeCreatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new LikeCreatedEvent RecordBuilder
   */
  public static com.miniblog.like.avro.LikeCreatedEvent.Builder newBuilder(com.miniblog.like.avro.LikeCreatedEvent other) {
    if (other == null) {
      return new com.miniblog.like.avro.LikeCreatedEvent.Builder();
    } else {
      return new com.miniblog.like.avro.LikeCreatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for LikeCreatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LikeCreatedEvent>
    implements org.apache.avro.data.RecordBuilder<LikeCreatedEvent> {

    private java.lang.CharSequence likeUuid;
    private java.lang.CharSequence postUuid;
    private java.lang.CharSequence userUuid;
    private long createdDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.miniblog.like.avro.LikeCreatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.likeUuid)) {
        this.likeUuid = data().deepCopy(fields()[0].schema(), other.likeUuid);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.postUuid)) {
        this.postUuid = data().deepCopy(fields()[1].schema(), other.postUuid);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.userUuid)) {
        this.userUuid = data().deepCopy(fields()[2].schema(), other.userUuid);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.createdDate)) {
        this.createdDate = data().deepCopy(fields()[3].schema(), other.createdDate);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing LikeCreatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.miniblog.like.avro.LikeCreatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.likeUuid)) {
        this.likeUuid = data().deepCopy(fields()[0].schema(), other.likeUuid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.postUuid)) {
        this.postUuid = data().deepCopy(fields()[1].schema(), other.postUuid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userUuid)) {
        this.userUuid = data().deepCopy(fields()[2].schema(), other.userUuid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.createdDate)) {
        this.createdDate = data().deepCopy(fields()[3].schema(), other.createdDate);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'likeUuid' field.
      * @return The value.
      */
    public java.lang.CharSequence getLikeUuid() {
      return likeUuid;
    }


    /**
      * Sets the value of the 'likeUuid' field.
      * @param value The value of 'likeUuid'.
      * @return This builder.
      */
    public com.miniblog.like.avro.LikeCreatedEvent.Builder setLikeUuid(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.likeUuid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'likeUuid' field has been set.
      * @return True if the 'likeUuid' field has been set, false otherwise.
      */
    public boolean hasLikeUuid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'likeUuid' field.
      * @return This builder.
      */
    public com.miniblog.like.avro.LikeCreatedEvent.Builder clearLikeUuid() {
      likeUuid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'postUuid' field.
      * @return The value.
      */
    public java.lang.CharSequence getPostUuid() {
      return postUuid;
    }


    /**
      * Sets the value of the 'postUuid' field.
      * @param value The value of 'postUuid'.
      * @return This builder.
      */
    public com.miniblog.like.avro.LikeCreatedEvent.Builder setPostUuid(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.postUuid = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'postUuid' field has been set.
      * @return True if the 'postUuid' field has been set, false otherwise.
      */
    public boolean hasPostUuid() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'postUuid' field.
      * @return This builder.
      */
    public com.miniblog.like.avro.LikeCreatedEvent.Builder clearPostUuid() {
      postUuid = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'userUuid' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserUuid() {
      return userUuid;
    }


    /**
      * Sets the value of the 'userUuid' field.
      * @param value The value of 'userUuid'.
      * @return This builder.
      */
    public com.miniblog.like.avro.LikeCreatedEvent.Builder setUserUuid(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.userUuid = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'userUuid' field has been set.
      * @return True if the 'userUuid' field has been set, false otherwise.
      */
    public boolean hasUserUuid() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'userUuid' field.
      * @return This builder.
      */
    public com.miniblog.like.avro.LikeCreatedEvent.Builder clearUserUuid() {
      userUuid = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdDate' field.
      * @return The value.
      */
    public long getCreatedDate() {
      return createdDate;
    }


    /**
      * Sets the value of the 'createdDate' field.
      * @param value The value of 'createdDate'.
      * @return This builder.
      */
    public com.miniblog.like.avro.LikeCreatedEvent.Builder setCreatedDate(long value) {
      validate(fields()[3], value);
      this.createdDate = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'createdDate' field has been set.
      * @return True if the 'createdDate' field has been set, false otherwise.
      */
    public boolean hasCreatedDate() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'createdDate' field.
      * @return This builder.
      */
    public com.miniblog.like.avro.LikeCreatedEvent.Builder clearCreatedDate() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LikeCreatedEvent build() {
      try {
        LikeCreatedEvent record = new LikeCreatedEvent();
        record.likeUuid = fieldSetFlags()[0] ? this.likeUuid : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.postUuid = fieldSetFlags()[1] ? this.postUuid : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.userUuid = fieldSetFlags()[2] ? this.userUuid : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.createdDate = fieldSetFlags()[3] ? this.createdDate : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LikeCreatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<LikeCreatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LikeCreatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<LikeCreatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.likeUuid);

    out.writeString(this.postUuid);

    out.writeString(this.userUuid);

    out.writeLong(this.createdDate);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.likeUuid = in.readString(this.likeUuid instanceof Utf8 ? (Utf8)this.likeUuid : null);

      this.postUuid = in.readString(this.postUuid instanceof Utf8 ? (Utf8)this.postUuid : null);

      this.userUuid = in.readString(this.userUuid instanceof Utf8 ? (Utf8)this.userUuid : null);

      this.createdDate = in.readLong();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.likeUuid = in.readString(this.likeUuid instanceof Utf8 ? (Utf8)this.likeUuid : null);
          break;

        case 1:
          this.postUuid = in.readString(this.postUuid instanceof Utf8 ? (Utf8)this.postUuid : null);
          break;

        case 2:
          this.userUuid = in.readString(this.userUuid instanceof Utf8 ? (Utf8)this.userUuid : null);
          break;

        case 3:
          this.createdDate = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










