apiVersion: v1
kind: Service
metadata:
  namespace: miniblog
  name: query-service-service
spec:
  selector:
    app: query-service-deployment
  ports:
    - protocol: TCP
      port: 4043
      targetPort: 4043
  type: ClusterIP
