apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry-deployment
  namespace: miniblog
  labels:
    app: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.5.0
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "schema-registry-service"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "broker-service:9092"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service
  namespace: miniblog
  labels:
    app: schema-registry
spec:
  selector:
    app: schema-registry
  ports:
    - name: schema-registry
      protocol: TCP
      port: 8085
      targetPort: 8081