apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: miniblog
  labels:
    app: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - name: client
      protocol: TCP
      port: 2181
      targetPort: 2181
