namespace: miniblog

replicaCount: 1

image:
  repository: 017820660901.dkr.ecr.ap-northeast-2.amazonaws.com/blog-front
  tag: latest
  pullPolicy: Always

service:
  port: 80
  targetPort: 80
  type: NodePort