apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: miniblog
  name: image-service-deployment
  labels:
    app: image-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service-deployment
  template:
    metadata:
      labels:
        app: image-service-deployment
    spec:
      containers:
        - name: image-service
          image: 017820660901.dkr.ecr.ap-northeast-2.amazonaws.com/image-service:latest
          ports:
            - containerPort: 4041
          env:
            - name: SPRING_APPLICATION_NAME
              value: "image-service"
            - name: SERVER_PORT
              value: "4041"
            - name: LOKI_URL
              value: "http://loki:3100/loki/api/v1/push"
            - name: AWS_S3_BUCKET
              value: "images.ghtjr.com"
            - name: AWS_REGION
              value: "ap-northeast-2"
            - name: AWS_ACCESSKEYID
              value: ""
            - name: AWS_SECRETACCESSKEY
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  namespace: miniblog
  name: image-service-service
spec:
  selector:
    app: image-service-deployment
  ports:
    - protocol: TCP
      port: 4041
      targetPort: 4041
  type: ClusterIP
