apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: miniblog
  name: musical-front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: musical-front-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: musical-front-deployment
    spec:
      containers:
        - image: 017820660901.dkr.ecr.ap-northeast-2.amazonaws.com/musical-front:latest
          imagePullPolicy: Always
          name: musical-front-deployment
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: miniblog
  name: musical-front-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: musical-front-deployment