apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: miniblog
  name: post-service-deployment
  labels:
    app: post-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service-deployment
  template:
    metadata:
      labels:
        app: post-service-deployment
    spec:
      containers:
        - name: post-service
          image: 017820660901.dkr.ecr.ap-northeast-2.amazonaws.com/post-service:latest
          ports:
            - containerPort: 4042
          env:
            - name: SPRING_APPLICATION_NAME
              value: "post-service"
            - name: SERVER_PORT
              value: "4042"
            - name: LOKI_URL
              value: "http://loki:3100/loki/api/v1/push"
            - name: SPRING_DATASOURCE_URI
              value: ""
            - name: SPRING_DATASOURCE_USERNAME
              value: ""
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "com.mysql.cj.jdbc.Driver"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "broker-service:9092"
            - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
              value: "org.apache.kafka.common.serialization.StringSerializer"
            - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
              value: "io.confluent.kafka.serializers.KafkaAvroSerializer"
            - name: SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL
              value: "http://schema-registry-service:8085"
            - name: POST_CREATED_EVENT_TOPIC_NAME
              value: "post.created"
---
apiVersion: v1
kind: Service
metadata:
  namespace: miniblog
  name: post-service-service
spec:
  selector:
    app: post-service-deployment
  ports:
    - protocol: TCP
      port: 4042
      targetPort: 4042
  type: ClusterIP
