apiVersion: v1
kind: Service
metadata:
  namespace: miniblog
  name: comment-service-service
spec:
  selector:
    app: comment-service-deployment
  ports:
    - protocol: TCP
      port: 4044
      targetPort: 4044
  type: ClusterIP
