apiVersion: v1
kind: Service
metadata:
  namespace: miniblog
  name: viewcount-service-service
spec:
  selector:
    app: viewcount-service-deployment
  ports:
    - protocol: TCP
      port: 4047
      targetPort: 4047
  type: ClusterIP
