apiVersion: v1
kind: Service
metadata:
  namespace: miniblog
  name: image-service-service
spec:
  selector:
    app: image-service-deployment
  ports:
    - protocol: TCP
      port: 4041
      targetPort: 4041
  type: ClusterIP
