/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.miniblog.post.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PostUpdatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7160913537968669967L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PostUpdatedEvent\",\"namespace\":\"com.miniblog.post.avro\",\"fields\":[{\"name\":\"postUuid\",\"type\":\"string\"},{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"content\",\"type\":\"string\"},{\"name\":\"updatedDate\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PostUpdatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PostUpdatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PostUpdatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PostUpdatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PostUpdatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PostUpdatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PostUpdatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PostUpdatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PostUpdatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence postUuid;
  private java.lang.CharSequence title;
  private java.lang.CharSequence content;
  private long updatedDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PostUpdatedEvent() {}

  /**
   * All-args constructor.
   * @param postUuid The new value for postUuid
   * @param title The new value for title
   * @param content The new value for content
   * @param updatedDate The new value for updatedDate
   */
  public PostUpdatedEvent(java.lang.CharSequence postUuid, java.lang.CharSequence title, java.lang.CharSequence content, java.lang.Long updatedDate) {
    this.postUuid = postUuid;
    this.title = title;
    this.content = content;
    this.updatedDate = updatedDate;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return postUuid;
    case 1: return title;
    case 2: return content;
    case 3: return updatedDate;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: postUuid = (java.lang.CharSequence)value$; break;
    case 1: title = (java.lang.CharSequence)value$; break;
    case 2: content = (java.lang.CharSequence)value$; break;
    case 3: updatedDate = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'postUuid' field.
   * @return The value of the 'postUuid' field.
   */
  public java.lang.CharSequence getPostUuid() {
    return postUuid;
  }


  /**
   * Sets the value of the 'postUuid' field.
   * @param value the value to set.
   */
  public void setPostUuid(java.lang.CharSequence value) {
    this.postUuid = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'content' field.
   * @return The value of the 'content' field.
   */
  public java.lang.CharSequence getContent() {
    return content;
  }


  /**
   * Sets the value of the 'content' field.
   * @param value the value to set.
   */
  public void setContent(java.lang.CharSequence value) {
    this.content = value;
  }

  /**
   * Gets the value of the 'updatedDate' field.
   * @return The value of the 'updatedDate' field.
   */
  public long getUpdatedDate() {
    return updatedDate;
  }


  /**
   * Sets the value of the 'updatedDate' field.
   * @param value the value to set.
   */
  public void setUpdatedDate(long value) {
    this.updatedDate = value;
  }

  /**
   * Creates a new PostUpdatedEvent RecordBuilder.
   * @return A new PostUpdatedEvent RecordBuilder
   */
  public static com.miniblog.post.avro.PostUpdatedEvent.Builder newBuilder() {
    return new com.miniblog.post.avro.PostUpdatedEvent.Builder();
  }

  /**
   * Creates a new PostUpdatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PostUpdatedEvent RecordBuilder
   */
  public static com.miniblog.post.avro.PostUpdatedEvent.Builder newBuilder(com.miniblog.post.avro.PostUpdatedEvent.Builder other) {
    if (other == null) {
      return new com.miniblog.post.avro.PostUpdatedEvent.Builder();
    } else {
      return new com.miniblog.post.avro.PostUpdatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new PostUpdatedEvent RecordBuilder by copying an existing PostUpdatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new PostUpdatedEvent RecordBuilder
   */
  public static com.miniblog.post.avro.PostUpdatedEvent.Builder newBuilder(com.miniblog.post.avro.PostUpdatedEvent other) {
    if (other == null) {
      return new com.miniblog.post.avro.PostUpdatedEvent.Builder();
    } else {
      return new com.miniblog.post.avro.PostUpdatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for PostUpdatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PostUpdatedEvent>
    implements org.apache.avro.data.RecordBuilder<PostUpdatedEvent> {

    private java.lang.CharSequence postUuid;
    private java.lang.CharSequence title;
    private java.lang.CharSequence content;
    private long updatedDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.miniblog.post.avro.PostUpdatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.postUuid)) {
        this.postUuid = data().deepCopy(fields()[0].schema(), other.postUuid);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.content)) {
        this.content = data().deepCopy(fields()[2].schema(), other.content);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.updatedDate)) {
        this.updatedDate = data().deepCopy(fields()[3].schema(), other.updatedDate);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing PostUpdatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.miniblog.post.avro.PostUpdatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.postUuid)) {
        this.postUuid = data().deepCopy(fields()[0].schema(), other.postUuid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.content)) {
        this.content = data().deepCopy(fields()[2].schema(), other.content);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.updatedDate)) {
        this.updatedDate = data().deepCopy(fields()[3].schema(), other.updatedDate);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'postUuid' field.
      * @return The value.
      */
    public java.lang.CharSequence getPostUuid() {
      return postUuid;
    }


    /**
      * Sets the value of the 'postUuid' field.
      * @param value The value of 'postUuid'.
      * @return This builder.
      */
    public com.miniblog.post.avro.PostUpdatedEvent.Builder setPostUuid(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.postUuid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'postUuid' field has been set.
      * @return True if the 'postUuid' field has been set, false otherwise.
      */
    public boolean hasPostUuid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'postUuid' field.
      * @return This builder.
      */
    public com.miniblog.post.avro.PostUpdatedEvent.Builder clearPostUuid() {
      postUuid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public com.miniblog.post.avro.PostUpdatedEvent.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.title = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public com.miniblog.post.avro.PostUpdatedEvent.Builder clearTitle() {
      title = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'content' field.
      * @return The value.
      */
    public java.lang.CharSequence getContent() {
      return content;
    }


    /**
      * Sets the value of the 'content' field.
      * @param value The value of 'content'.
      * @return This builder.
      */
    public com.miniblog.post.avro.PostUpdatedEvent.Builder setContent(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.content = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'content' field has been set.
      * @return True if the 'content' field has been set, false otherwise.
      */
    public boolean hasContent() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'content' field.
      * @return This builder.
      */
    public com.miniblog.post.avro.PostUpdatedEvent.Builder clearContent() {
      content = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'updatedDate' field.
      * @return The value.
      */
    public long getUpdatedDate() {
      return updatedDate;
    }


    /**
      * Sets the value of the 'updatedDate' field.
      * @param value The value of 'updatedDate'.
      * @return This builder.
      */
    public com.miniblog.post.avro.PostUpdatedEvent.Builder setUpdatedDate(long value) {
      validate(fields()[3], value);
      this.updatedDate = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'updatedDate' field has been set.
      * @return True if the 'updatedDate' field has been set, false otherwise.
      */
    public boolean hasUpdatedDate() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'updatedDate' field.
      * @return This builder.
      */
    public com.miniblog.post.avro.PostUpdatedEvent.Builder clearUpdatedDate() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PostUpdatedEvent build() {
      try {
        PostUpdatedEvent record = new PostUpdatedEvent();
        record.postUuid = fieldSetFlags()[0] ? this.postUuid : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.title = fieldSetFlags()[1] ? this.title : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.content = fieldSetFlags()[2] ? this.content : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.updatedDate = fieldSetFlags()[3] ? this.updatedDate : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PostUpdatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<PostUpdatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PostUpdatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<PostUpdatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.postUuid);

    out.writeString(this.title);

    out.writeString(this.content);

    out.writeLong(this.updatedDate);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.postUuid = in.readString(this.postUuid instanceof Utf8 ? (Utf8)this.postUuid : null);

      this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);

      this.content = in.readString(this.content instanceof Utf8 ? (Utf8)this.content : null);

      this.updatedDate = in.readLong();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.postUuid = in.readString(this.postUuid instanceof Utf8 ? (Utf8)this.postUuid : null);
          break;

        case 1:
          this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);
          break;

        case 2:
          this.content = in.readString(this.content instanceof Utf8 ? (Utf8)this.content : null);
          break;

        case 3:
          this.updatedDate = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










