apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service
  namespace: miniblog
  labels:
    app: schema-registry
spec:
  selector:
    app: schema-registry
  ports:
    - name: schema-registry
      protocol: TCP
      port: 8085
      targetPort: 8081
