/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.miniblog.comment.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CommentDeletedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7458892931456087477L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CommentDeletedEvent\",\"namespace\":\"com.miniblog.comment.avro\",\"fields\":[{\"name\":\"commentUuid\",\"type\":\"string\"},{\"name\":\"postUuid\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CommentDeletedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CommentDeletedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CommentDeletedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CommentDeletedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CommentDeletedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CommentDeletedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CommentDeletedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CommentDeletedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CommentDeletedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence commentUuid;
  private java.lang.CharSequence postUuid;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CommentDeletedEvent() {}

  /**
   * All-args constructor.
   * @param commentUuid The new value for commentUuid
   * @param postUuid The new value for postUuid
   */
  public CommentDeletedEvent(java.lang.CharSequence commentUuid, java.lang.CharSequence postUuid) {
    this.commentUuid = commentUuid;
    this.postUuid = postUuid;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return commentUuid;
    case 1: return postUuid;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: commentUuid = (java.lang.CharSequence)value$; break;
    case 1: postUuid = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'commentUuid' field.
   * @return The value of the 'commentUuid' field.
   */
  public java.lang.CharSequence getCommentUuid() {
    return commentUuid;
  }


  /**
   * Sets the value of the 'commentUuid' field.
   * @param value the value to set.
   */
  public void setCommentUuid(java.lang.CharSequence value) {
    this.commentUuid = value;
  }

  /**
   * Gets the value of the 'postUuid' field.
   * @return The value of the 'postUuid' field.
   */
  public java.lang.CharSequence getPostUuid() {
    return postUuid;
  }


  /**
   * Sets the value of the 'postUuid' field.
   * @param value the value to set.
   */
  public void setPostUuid(java.lang.CharSequence value) {
    this.postUuid = value;
  }

  /**
   * Creates a new CommentDeletedEvent RecordBuilder.
   * @return A new CommentDeletedEvent RecordBuilder
   */
  public static com.miniblog.comment.avro.CommentDeletedEvent.Builder newBuilder() {
    return new com.miniblog.comment.avro.CommentDeletedEvent.Builder();
  }

  /**
   * Creates a new CommentDeletedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CommentDeletedEvent RecordBuilder
   */
  public static com.miniblog.comment.avro.CommentDeletedEvent.Builder newBuilder(com.miniblog.comment.avro.CommentDeletedEvent.Builder other) {
    if (other == null) {
      return new com.miniblog.comment.avro.CommentDeletedEvent.Builder();
    } else {
      return new com.miniblog.comment.avro.CommentDeletedEvent.Builder(other);
    }
  }

  /**
   * Creates a new CommentDeletedEvent RecordBuilder by copying an existing CommentDeletedEvent instance.
   * @param other The existing instance to copy.
   * @return A new CommentDeletedEvent RecordBuilder
   */
  public static com.miniblog.comment.avro.CommentDeletedEvent.Builder newBuilder(com.miniblog.comment.avro.CommentDeletedEvent other) {
    if (other == null) {
      return new com.miniblog.comment.avro.CommentDeletedEvent.Builder();
    } else {
      return new com.miniblog.comment.avro.CommentDeletedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for CommentDeletedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CommentDeletedEvent>
    implements org.apache.avro.data.RecordBuilder<CommentDeletedEvent> {

    private java.lang.CharSequence commentUuid;
    private java.lang.CharSequence postUuid;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.miniblog.comment.avro.CommentDeletedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.commentUuid)) {
        this.commentUuid = data().deepCopy(fields()[0].schema(), other.commentUuid);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.postUuid)) {
        this.postUuid = data().deepCopy(fields()[1].schema(), other.postUuid);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing CommentDeletedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.miniblog.comment.avro.CommentDeletedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.commentUuid)) {
        this.commentUuid = data().deepCopy(fields()[0].schema(), other.commentUuid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.postUuid)) {
        this.postUuid = data().deepCopy(fields()[1].schema(), other.postUuid);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'commentUuid' field.
      * @return The value.
      */
    public java.lang.CharSequence getCommentUuid() {
      return commentUuid;
    }


    /**
      * Sets the value of the 'commentUuid' field.
      * @param value The value of 'commentUuid'.
      * @return This builder.
      */
    public com.miniblog.comment.avro.CommentDeletedEvent.Builder setCommentUuid(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.commentUuid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'commentUuid' field has been set.
      * @return True if the 'commentUuid' field has been set, false otherwise.
      */
    public boolean hasCommentUuid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'commentUuid' field.
      * @return This builder.
      */
    public com.miniblog.comment.avro.CommentDeletedEvent.Builder clearCommentUuid() {
      commentUuid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'postUuid' field.
      * @return The value.
      */
    public java.lang.CharSequence getPostUuid() {
      return postUuid;
    }


    /**
      * Sets the value of the 'postUuid' field.
      * @param value The value of 'postUuid'.
      * @return This builder.
      */
    public com.miniblog.comment.avro.CommentDeletedEvent.Builder setPostUuid(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.postUuid = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'postUuid' field has been set.
      * @return True if the 'postUuid' field has been set, false otherwise.
      */
    public boolean hasPostUuid() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'postUuid' field.
      * @return This builder.
      */
    public com.miniblog.comment.avro.CommentDeletedEvent.Builder clearPostUuid() {
      postUuid = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CommentDeletedEvent build() {
      try {
        CommentDeletedEvent record = new CommentDeletedEvent();
        record.commentUuid = fieldSetFlags()[0] ? this.commentUuid : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.postUuid = fieldSetFlags()[1] ? this.postUuid : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CommentDeletedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<CommentDeletedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CommentDeletedEvent>
    READER$ = (org.apache.avro.io.DatumReader<CommentDeletedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.commentUuid);

    out.writeString(this.postUuid);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.commentUuid = in.readString(this.commentUuid instanceof Utf8 ? (Utf8)this.commentUuid : null);

      this.postUuid = in.readString(this.postUuid instanceof Utf8 ? (Utf8)this.postUuid : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.commentUuid = in.readString(this.commentUuid instanceof Utf8 ? (Utf8)this.commentUuid : null);
          break;

        case 1:
          this.postUuid = in.readString(this.postUuid instanceof Utf8 ? (Utf8)this.postUuid : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










